import {createContext, useContext, useCallback} from 'react';
export const LanguageContext = createContext('tr');
export const EN = {
'Model dosyası açılamadı.':'The model file could not be loaded.',
'BRICKCRAFT STUDIO':'BRICKCRAFT STUDIO','KENDİ TARZINDA YAP.':'BUILD YOUR WAY.',
'Kişisel çalışma alanın':'Your personal workspace','Bu cihazda kayıtlı':'Saved on this device','Kayıt alanı dolu':'Could not save · export a copy','Tema seçimi':'Theme','Açık tema':'Light theme','Koyu tema':'Dark theme','Yapımı kaydet':'Export build','Pencereyi kapat':'Close dialog',
'Parçalar':'Parts','Araçlar':'Tools','Modeller':'Models','MALZEME DEPOSU':'PARTS LIBRARY','Parçaların':'Your pieces','Malzeme listesini aç':'Open parts inventory','Model parçaları':'Model pieces','Serbest yapım':'Free build','Parça veya numara ara':'Find a piece or part number','Parça ara':'Search parts','Aramayı temizle':'Clear search','Parça türü':'Part category','Tüm parçalar':'All pieces','Tuğla ve eğimler':'Bricks & slopes','Plakalar':'Plates & tiles','Teknik parçalar':'Technic','Renk filtresi':'Color filter','Tüm renkler':'All colors','parça çeşidi':'part types','Tut ve sürükle':'Grab & drag','Parçalar hazırlanıyor…':'Preparing pieces…','Bu aramada parça yok.':'No matching pieces.','Filtreleri temizle':'Clear filters',
'Sınırsız parça. Kendi tasarımını oluştur.':'Unlimited pieces. Create your own design.','Her parça, kaynak modelin gerçek geometrisi.':'Actual part geometry from the source model.','Yapım masası':'Build table','Yapım masam':'My build','Bitmiş model':'Finished model','Geri al (⌘Z)':'Undo (⌘Z)','İleri al (⌘⇧Z)':'Redo (⌘⇧Z)','Model yüklenemedi':'Could not load model','Atölyen hazırlanıyor':'Getting your workshop ready','Tekrar dene':'Try again',
'Şimdi sıra sende.':'Make it yours.','Soldan bir parçayı tut, masaya sürükle.':'Grab a piece on the left and drag it onto the table.','Çevir, birleştir, kendi ellerinle yap.':'Turn it, connect it, build with your own hands.','döndür':'rotate','ipucu':'hint','Bitmiş modeli inceliyorsun':'You are exploring the finished model','Yapıma dön':'Back to building','Parça elinde · Masaya tıkla veya sürükleyip bırak':'Piece in hand · Click the table or drag and drop','İptal':'Cancel','Bir küçük ipucu':'A little nudge','İpucunu kapat':'Close hint',
'Parçayı hedefte elime al':'Pick up at target','Bu parçaların hepsi masada. Hedefe taşımak için masadaki birini seç.':'All these pieces are on the table. Select one to move it to the target.','Yerleştirmek için masaya tıkla. İstersen konumunu değiştir.':'Click the table to place it, or drag to change its position.','Tüm hedef parçaları yerleştirdin. Eline sağlık!':'Every target piece is in place. Beautifully built!',
'Taşıma aracı':'Move tool','Taşı':'Move','Döndürme halkalarını aç':'Show rotation rings','Çevir':'Rotate','İzometrik görünüm ve ortala':'Isometric view and fit','Üstten görünüm':'Top view','Önden görünüm':'Front view','Çalışmayı ekrana sığdır':'Fit build to screen','Izgaraya hizala':'Snap to grid','İpucu iste':'Get a hint','PARÇA KONTROLÜ':'PIECE CONTROLS','Elindeki parça':'Selected piece','Tut. Çevir. Yerleştir.':'Grab. Turn. Place.','Masadaki bir parçaya veya depodaki parçalardan birine dokun.':'Select a piece on the table or pick one from the library.',
'DÖNDÜR':'ROTATE','Her tıklama 90°':'90° per click','YÜKSEKLİK':'HEIGHT','1 kademe = 1 plaka':'1 step = 1 plate','Bir plaka aşağı':'One plate down','Bir plaka yukarı':'One plate up','Hassas konum':'Precise position','Kopyala':'Duplicate','Kaldır':'Remove','YAPTIĞIN MODEL':'YOUR MODEL','Değiştir':'Change','Bitmiş modeli 3 boyutlu incele':'Explore the finished model in 3D','3B incele':'Explore 3D','kaynak parça':'source pieces','masada':'on table','parça hedefe yerleşti':'pieces at target','Tasarımcı ve kaynak bilgileri':'Designer & source credits','Kontroller ve kısayollar':'Controls & shortcuts',
'Bir parça elinde':'Holding a piece','Model inceleme':'Exploring model','Yapım alanı':'Building','parça':'pieces','Boş alanda sürükle: kamerayı çevir':'Drag empty space: orbit','Tekerlek: yakınlaş':'Scroll: zoom','Sağ tuş: kaydır':'Right drag: pan','Kısayollar':'Shortcuts','Parça seçildi. Masaya yerleştirebilirsin.':'Piece selected. You can place it on the table.',
'Bir sonraki yapını seç.':'What will you build next?','Gerçek parça geometrileri. Detaylı tasarımlar. Baştan sona senin yapımın.':'Real pieces. Detailed designs. Built by you, from the very first brick.','Parça sayıları model dosyalarından hesaplanır. Her modeldeki yapımın ayrı kaydedilir.':'Counts come from source files. Your progress is saved separately for every model.',
'Malzeme listen':'Your parts inventory','CSV indir':'Download CSV','Parça':'Part','Renk':'Color','Gereken':'Required','Masada':'On table','Kalan':'Remaining','Modelin hikâyesi ve kaynakları':'The story & sources','Tasarımcı:':'Designer:','Bu modelin lisansı:':'Model license:',
'. Parça geometrileri LDraw topluluk kütüphanesinden gelir; özgün yazar ve lisans bilgileri dosyalarda korunur.':'. Part geometry comes from the LDraw community library. Original author and license details are retained in the files.',
'Alt gruplar ayrı, hareket ettirilebilir parçalara dönüştürüldü. Bu bir topluluk yapım aracıdır; LEGO Group ile bağlantılı değildir.':'Subassemblies have been converted to individually movable pieces. This community building tool is not affiliated with the LEGO Group.',
'Özgün model sayfası':'Original model page','Kaynak MPD':'Source MPD','LDraw lisans bilgileri':'LDraw license details','Masanın kontrolü sende.':'Your table. Your rules.','Tut ve yerleştir':'Grab & place','Çevir ve birleştir':'Turn & connect','İstediğin zaman yardım al':'Help when you want it',
'Depodaki parçayı masaya sürükle. Masadaki parçayı tekrar tutup taşı. Klavyeyle parça seçmek için Enter, yerleştirmek için masaya tıkla.':'Drag a library piece onto the table. Grab any placed piece to move it again. Press Enter on a library piece to pick it up, then click the table to place it.',
'“Çevir” aracını aç, parçanın çevresindeki halkaları tutup döndür. R ile yatay, Shift + R ile X ekseninde döndür. Sağdaki X / Y / Z kontrollerini kullan. Ok tuşlarıyla yüksekliği bir plaka değiştir. Izgaraya hizala açıkken halkalar 15° aralıklarla döner; kapalıyken serbesttir.':'Use Rotate to drag the rings around a piece. R turns horizontally, Shift + R turns on X. Use the X / Y / Z controls for quarter turns. Up and Down change height by one plate. Rings snap to 15° when grid snapping is enabled.',
'H ile örnek konumu gör. “Parçayı hedefte elime al” konum ve yönü hazırlar; yerleştirmek için yine sen tıklarsın.':'Press H to reveal a target. Pick up at target prepares the position and orientation. You still place the piece yourself.',
'Geri al':'Undo','Parçayı kaldır':'Remove piece','Elindeki parçayı bırak':'Cancel held piece','Kamerayı kaydır':'Pan camera','Sağ tuş':'Right button','Yapım dosyası aç':'Import build','Masayı temizle':'Clear table','Vazgeç':'Cancel',
'Bu parçaların hepsi masada. Daha fazlası için serbest yapımı seç.':'All of these pieces are on the table. Switch to Free build for more.','Bu dosya farklı bir modele ait. Önce ilgili modeli aç.':'This file belongs to a different model. Open that model first.','Dosyada geçersiz parçalar var.':'The file contains invalid pieces.','Yapım dosyan açıldı.':'Build imported.','Dosya açılamadı.':'Could not open file.',
'Eyfel Kulesi':'Eiffel Tower','Çiçek Buketi':'Flower Bouquet','TOPLULUK TASARIMI':'COMMUNITY DESIGN','İleri seviye':'Advanced','Orta seviye':'Intermediate','Uzman':'Expert',
'Motorundan açılan kapılarına, bir otomobil klasiği.':'An automotive icon, from its engine to its opening doors.','Paris’in simgesi. Kemerleri ve katlarıyla özgün model.':'The Paris landmark, with its iconic arches and platforms.','Odaları, çatısı ve araçlarıyla detaylı bir şehir evi.':'A detailed city home with rooms, roof and vehicles.','Pembe çiçekler, kıvrılan dallar ve ahşap görünümlü bir kaide.':'Pink blossoms, winding branches and a wood-look display base.','Uzay mekiği, Hubble teleskobu ve sergileme standları.':'The space shuttle, Hubble telescope and display stands.','Güller, aslanağızları ve rengârenk çiçeklerden bir koleksiyon.':'A collection of roses, snapdragons and colorful blooms.',
'Yalnızca kalanlar':'Available only','Favoriler':'Favorites','Favoriye ekle':'Add to favorites','Favoriden çıkar':'Remove favorite','Yeni':'New','Tümü':'All','Araçlar ve uzay':'Vehicles & space','Mimari':'Architecture','Doğa':'Nature','Kaldığın yerden':'Continue building','Yeni bir başlangıç':'Start something new','Kayıtlı yapımın geri yüklendi.':'Your saved build has been restored.','Yedek kayıt kurtarıldı.':'Your backup has been recovered.','Son kayıt':'Last saved','Kaydediliyor…':'Saving…','Hazır':'Ready','Yalnızca bu tarayıcıda saklanır.':'Stored only in this browser.',
'Bu parçayı depoda bul':'Find this piece in library','Parçaya yaklaş (F)':'Focus selected piece (F)','Tabana indir':'Drop to table','Yan yana karşılaştır':'Compare side by side','Referansı gizle':'Hide reference','Model rehberi':'Model reference',
'Zemine hazır':'Ready on table','Yüzeye hizalandı':'Aligned to surface','Çıkıntılar hizalandı':'Studs aligned','Parçalar çakışıyor':'Pieces overlap','Serbest konum':'Free position','Hedefe hizalandı':'Aligned to target','Bu konumda parçalar çakışıyor. Parçayı başka yere taşı.':'Pieces overlap here. Move the piece to a clear position.',
'Düz tuğla ve plakalar, birbirlerinin çıkıntılarına hizalanır; gövdeler çakışıyorsa yerleştirme durdurulur. Özel parçalar için yüzey ve ızgara hizalaması kullanılır. Teknik pim ve menteşeler için fiziksel bağlantı doğrulaması henüz yok.':'Rectangular bricks and plates align to studs; overlapping bodies cannot be placed. Special pieces use surface and grid snapping. Technic pins and hinges do not yet have physical connection validation.',
'Ferrari modelinde çıkartmalar bulunmuyor. Dosyada 1.157 öğe var; kutu üzerindeki parça sayısıyla farklılık gösterebilir.':'The Ferrari model has no stickers. Its source contains 1,157 elements, which may differ from the box inventory.',
'Kulenin esnek aks geometrisi kaynak dosyadaki şekliyle korunur.':'The tower’s flexible axle retains its original source geometry.',
'GitHub’daki Carriage House tasarımının mimari parçaları, odaları ve araçları birlikte aktarılmıştır. Karbonit desenli parçada geometrik baskı kullanılır; küçük baskı ayrıntıları farklı olabilir.':'Carriage House includes its architectural details, rooms and vehicles. The carbonite printed piece uses geometric artwork; small print details may differ.',
'Discovery, Hubble teleskobu açık konumdayken gösterilir. Kaynakta teleskop bağlantı braketi ve katlı güneş paneli boruları yoktur. Bazı bilgi etiketlerinin görselleri kaynakta bulunmaz.':'Discovery includes Hubble in its deployed position. The source omits the telescope attachment bracket and stowed solar-array tubes. Some information label images are absent from the source.',
'Sakura varyantı, pembe çiçekleri ve sergileme kaidesiyle aktarılmıştır.':'The cherry blossom variant includes pink blooms and its display base.',
'Buketteki tüm çiçekler ayrı hareket ettirilebilir parçalardan oluşur.':'Every flower in the bouquet is built from individually movable pieces.',
'{count} parça masada.':'{count} pieces on the table.','{name} tamamlanmış 3B model':'{name} finished 3D model','Model hazırlanıyor':'Preparing model','Gerçek parça geometrileri yükleniyor · %{percent}':'Loading real part geometry · {percent}%','{axis} ekseninde döndür':'Rotate around {axis}','{axis} konumu':'{axis} position','{count} plaka':'{count} plates','{count} adet':'{count} available','Tut ve masaya sürükle. Klavyeyle seçmek için Enter.':'Drag onto the table. Press Enter to pick up with the keyboard.','parçasının örnek konumu masada saydam olarak görünüyor.':'is shown as a transparent target on the table.','Masadaki {count} parça depoya dönecek. Bu işlemi geri alabilirsin.':'The {count} pieces on your table will return to the library. You can undo this.',
'3 boyutlu LEGO yapım alanı':'3D LEGO building area','parça / renk çeşidi':'part / color combinations','D':'D','Dil seçimi':'Language selection'
};
export function translate(language, key, values={}) {
  const template=language==='en' ? EN[key] ?? key : key;
  const text=language==='en' && Number(values.count)===1 ? template.replace(/\bpieces\b/g,'piece').replace(/\bplates\b/g,'plate') : template;
  return text.replace(/\{(\w+)\}/g,(_,name)=>values[name]??`{${name}}`);
}
export function useLanguage() {
  const language=useContext(LanguageContext);
  const t=useCallback((key,values)=>translate(language,key,values),[language]);
  return {language,t};
}
